### PR TITLE
Building

### PR DESCRIPTION
**Pull request by ln5**
These changes have helped me getting things built and qemu booting, starting from a fresh Debian Buster system.

Still haven't booted all the way due to network configuration issues local to my build environment. So more changes might appear.

### CODE REVIEW

**Comment by jensdrenhaus** [comment]
I like the idea to use environment variables. However, customizing the provisioning server has been solved in one of the last commits. Please rebase onto the current master.

**Comment by ln5** [comment]
Since there are more configuration knobs than only provisioning server config, should we collect them all in a single configuration file? Given some comments in that file it would serve as a good place for getting a picture of what can be configured.

**Comment by ln5** [comment]
Then again, there's certainly an argument for keeping each subdirectory selfcontained.
I'll hold off putting the two config knobs mentioned in any file for now, and just add info about them to the toplevel README.

**Comment by ln5** [comment]
See #23

**Pull request closed without merging**
