### PR TITLE
Support precompiled kernel

### PR DESCRIPTION
**Pull request by sylv-io**

### CODE REVIEW

**Comment by jensdrenhaus** [comment]
What is going on here? 
Still work in progress?

**Comment by bjoto** [comment]
Hey! Tried "task iso" with this config
```
# System Transparency build configuration.

##############################################################################
# Tooling
#
# Following configuration is used during the installation of the tools.
##############################################################################
# ST_UROOT_VERSION defines the branch, tag or commit for u-root command.
# repository: https://github.com/u-root/u-root
#
ST_UROOT_VERSION=b56464f

# ST_STBOOT_VERSION defines the branch, tag or commit for stboot bootloader.
# repository: https://github.com/system-transparency/stboot
#
ST_STBOOT_VERSION=880b21f

# ST_STMGR_VERSION defines the branch, tag or commit for th stmgr command.
# repository: https://github.com/system-transparency/stmgr
#
#ST_STMGR_VERSION=1c1394b

# ST_CPU_VERSION defines the branch, tag or commit for cpu command.
# repository: https://github.com/system-transparency/stmgr
#
#ST_CPU_VERSION=a901912

##############################################################################
# stboot installation image
#
# Following options controls the creation of the stboot installation image. 
# This includes the LinuxBoot kernel and initramfs, the host- and security
# configuration files and further files and paramters.
##############################################################################

# ST_STBOOT_ARGS defines additional stboot command-line arguments.

ST_STBOOT_ARGS="-debug -klog"

# ST_LINUXBOOT_KERNEL_VERSION defines the linux kernel version of the LinuxBoot
# distribution.
#
ST_LINUXBOOT_KERNEL_VERSION=5.15.21

# ST_LINUXBOOT_KERNEL_CONFIG is the linux kernel defconfig loaded before
# the kernel is beeing built.
#
# ST_LINUXBOOT_KERNEL_CONFIG="contrib/linuxboot.defconfig"

# ST_LINUXBOOT_VARIANT determines the content of the initramfs. Possible values
# are: minimal, debug and full.
#
# minimal: The only executables included in the initramfs are its init routine
# and the stboot binary.
#
# debug: in addition to minimal it includes a shell(elvish), the cpud command
# from the u-root repositore for debugging, a elvish script to bring up
# network, keys used with cpud and a elvish script to launch a remote debugging
# session via cpud.
#
# full: in addition to debug all core utilities of u-root.
#
ST_LINUXBOOT_VARIANT=minimal

# ST_LINUXBOOT_CMDLINE controls the kernel command-line of the LinuxBoot kernel.
#
ST_LINUXBOOT_CMDLINE="console=tty0 console=ttyS0,115200 printk.devkmsg=on"

# ST_SIGNING_ROOT is the path to a PEM encoded root certificate used for
# signature verification of the OS packages. The root certificate is included
# into the LinuxBoot initramfs.
# ST_SIGNING_ROOT="out/keys/example_keys/root.cert"

# ST_HOST_CONFIG_MODE defines where the host configuration is stored inside the
# stboot installation.
#
# initramfs (default): Initramfs of LinuxBoot.
#
# cdrom (iso target only): ISO filesystem
#
# legacy (disk target only): STBOOT partition
#
# efivar: (U)EFI variable
#
ST_HOST_CONFIG_MODE="cdrom"

# ST_HOST_CONFIG_LOCATION defines the location of the host configuration inside
# the stboot installation. It defines either the path of the configuration file
# or in case it is set to "efivar" the EFI variable name. The mode "legacy"
# does not support this configuration option.
#
# "initramfs" and "cdrom" mode:
ST_HOST_CONFIG_LOCATION="/host_configuration.json"
# "efivar" mode:
#ST_HOST_CONFIG_LOCATION="STHostConfig-f401f2c1-b005-4be0-8cee-f2e5945bcbe7"

# ST_HOST_CONFIG_FILE is the local path where the host configuration file is
# taken from. It is not required, if ST_HOST_CONFIG_LOCATION is set to "efivar".
#
ST_HOST_CONFIG_FILE="contrib/example_host_configuration.json"

# ST_NUM_SIGNATURES defines the minimum number of signatures that must be valid
# in order to boot the operation system. The value is saved in the security
# configuration file inside the LinuxBoot initramfs.
#
#ST_NUM_SIGNATURES=2

# ST_BOOT_MODE controlls wether the OS package is loaded from the network
# or from local storage. The value is saved in the security configuration file
# inside the LinuxBoot initramfs.
#
ST_BOOT_MODE=network
#ST_BOOT_MODE=local


# ST_LOCAL_OSPKG_DIR chooses the directory location of the OS Packages. Only
# relevant if ST_BOOT_MODE=local. The path should contain at least one OS package
# archive file (ZIP) and descriptor file (JSON). In addition it is required to
# provide a "boot_order" with the OS package's archive file listed in it.
ST_LOCAL_OSPKG_DIR="out/ospkgs"

# ST_DATA_PARTITION_EXTRA_SPACE defines additional storage space of the data
# partition in bytes.
# Suffixes like 'K', 'M', 'G', 'T' are supported. (case insensitive)
# A minimum of 100M is recommended. (corresponds to 100 MiB). When using
# network boot mode and caching OS packages is enabled, it is recommended to 
# increase this value in order to have enough space to store an OS package.
#
ST_DATA_PARTITION_EXTRA_SPACE="100M"


##############################################################################
# stboot provisioningiso image
#
# Following options controls the creation of the stboot provisioning iso
# image.
##############################################################################

# ST_PROVISO_STMGR_ARGS defines the command-line arguments for stmgr.
ST_PROVISO_STMGR_ARGS="-efi"
ST_LINUXBOOT_KERNEL_CONFIG="/home/bjorn/src/mullvad/st-utils/kernel-config/linuxboot-config"
ST_SIGNING_ROOT=/home/bjorn/src/mullvad/stmgr/keys/root.cert
ST_NUM_SIGNATURES=1
ST_LINUXBOOT_CMDLINE="console=tty0 console=ttyS0,115200 printk.devkmsg=on"
```

and get for `task iso`

```
open /home/bjorn/src/mullvad/st-utils/work/system-transparency/out/artifacts/cmdline.txt: no such file or directory
task: Command "if [ -n "console=tty0 console=ttyS0,115200 printk.devkmsg=on" ]; then
  echo "console=tty0 console=ttyS0,115200 printk.devkmsg=on" > out/artifacts/cmdline.txt
  echo '--add-section .cmdline="out/artifacts/cmdline.txt" --c-section-vma .cmdline=0x30000'
fi
" failed: exit status 1
```

Do I need to change stuff in the config?

**Comment by sylv-io** [comment]
looks like a missing `mkdir -p` on my part.

**Comment by bjoto** [comment]
Same config, now I get: 
```
[linux:build] make[1]: *** No rule to make target '../../../out/artifacts/initramfs-linuxboot.cpio.gz', needed by 'usr/initramfs_inc_data'.  Stop.
[linux:build] make: *** [Makefile:1868: usr] Error 2
[linux:build] make: *** Waiting for unfinished jobs....
...
```

**Comment by bjoto** [comment]
A bit further:
```
[linux:build] make: Leaving directory '/home/bjorn/src/mullvad/st-utils/work/system-transparency/cache/linux/5_15_21'
task: [linux:kernel] mkdir -p $(dirname cache/linux/5_15_21)
task: [linux:kernel] cp ./cache/linux/5_15_21/arch/x86/boot/bzImage out/artifacts/vmlinux
task: [linux:efi] objcopy --add-section .cmdline="out/artifacts/cmdline.txt" --c-section-vma .cmdline=0x30000 --add-section .linux="out/artifacts/vmlinux" --change-section-vma .linux=0x2000000 --add-section .initrd="out/artifacts/stboot.cpio.gz" --change-section-vma .initrd=0x3000000 /usr/lib/systemd/boot/efi/linuxx64.efi.stub out/artifacts/stboot.efi

[linux:efi] objcopy: unrecognized option '--c-section-vma'

```

**Comment by MDr164** [comment]
Looks like a type in the Taskfile to me. I think it should have been `--change-section-vma` instead of `--c-section-vma`.

**Comment by MDr164** [comment]
It definitely should! Added it to my agenda.

**Comment by bjoto** [comment]
@sylv-io @jensdrenhaus and I discussed the next steps. @sylv-io noted that the current approach is a bit hacky, and will look into https://systemd.io/BOOT_LOADER_SPECIFICATION/ and this can be used.

**Comment by jensdrenhaus** [comment]
Further development on https://git.glasklar.is/system-transparency/core/system-transparency

**Pull request closed without merging**
