### PR TITLE
Feature native debos

### PR DESCRIPTION
**Pull request by sylv-io**
Support 3 types of debos environments:
- run native debos on debian based host (user needs kvm access)
- run debos in a docker container (user needs docker API access and host has kvm avaiable)
- run debos in a podman container (user needs kvm access)

* Add debos environment detection

Regression:
Host KVM support is necessary to build debos os

Additional changes:
- use relative path in make
- support multiple default configs
- Fix go targets

### CODE REVIEW

**Comment by jensdrenhaus** [comment]
remember to add all tools / cmds/ libs  nedded in `scripts/check.sh`

**Comment by sylv-io** [comment]
> remember to add all tools / cmds/ libs nedded in `scripts/check.sh`

looks like there are no new dependencies here :+1:

**Comment by sylv-io** [comment]
Regression: looks like efi does not boot :/

pls do not merge

**Comment by sylv-io** [comment]
> Regression: looks like efi does not boot :/
> 
> pls do not merge

done :+1:

**Comment by sylv-io** [comment]
Done. ready for review :+1:

**Review by jensdrenhaus — CHANGES_REQUESTED** [review]
Maybe we should delete run.sh now, since I guess it won't work anymore now?
Are you sure, nothing needs to be updated in the README.md?

**Pull request merged**
