### PR TITLE
stboot-installation: Fix efi and coreboot image build

### PR DESCRIPTION
**Pull request by sylv-io**
Commit 56d95e96 did change the calulation of the STDATA partition.
However it only adapts the MBR bootloader build script and therefor
breaks the coreboot/efi build. This commit adapts the missing changes.

Additional changes:
* fix file name typo (build_boot_fileystem.sh -> build_boot_filesystem.sh)
* make all scripts executable

Signed-off-by: Marcello Sylvester Bauer <sylv@sylv.io>

### CODE REVIEW

**Review by jensdrenhaus — COMMENTED** [review]
Why are this files in in PR:
`stboot-installation/common/build_default_local_boot_order.sh` (Empty file)
`stboot-installation/common/build_host_config.sh` (Empty file)
`.../coreboot-payload/build_boot_fileystem.sh → ...coreboot-payload/build_boot_filesystem.sh` (File renamed without changes)

**Comment by sylv-io** [comment]
since all the other scripts a executable, i adjusted `build_default_local_boot_order.sh` and `build_host_config.sh`. (chmod +x)
There is a typo in `build_boot_fileystem.sh` (missing s) :smile:

**Comment by sylv-io** [comment]
I updated the commit message :+1:

**Comment by jensdrenhaus** [comment]
:+1:

**Pull request merged**
